package com.lourish.wpoffer.domain;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * {@link Offers} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class OffersAssert extends AbstractObjectAssert<OffersAssert, Offers> {

  /**
   * Creates a new <code>{@link OffersAssert}</code> to make assertions on actual Offers.
   * @param actual the Offers we want to make assertions on.
   */
  public OffersAssert(Offers actual) {
    super(actual, OffersAssert.class);
  }

  /**
   * An entry point for OffersAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOffers)</code> and get specific assertion with code completion.
   * @param actual the Offers we want to make assertions on.
   * @return a new <code>{@link OffersAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static OffersAssert assertThat(Offers actual) {
    return new OffersAssert(actual);
  }

}
