package com.lourish.wpoffer.domain;

/**
 * {@link Offer} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractOfferAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class OfferAssert extends AbstractOfferAssert<OfferAssert, Offer> {

  /**
   * Creates a new <code>{@link OfferAssert}</code> to make assertions on actual Offer.
   * @param actual the Offer we want to make assertions on.
   */
  public OfferAssert(Offer actual) {
    super(actual, OfferAssert.class);
  }

  /**
   * An entry point for OfferAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOffer)</code> and get specific assertion with code completion.
   * @param actual the Offer we want to make assertions on.
   * @return a new <code>{@link OfferAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static OfferAssert assertThat(Offer actual) {
    return new OfferAssert(actual);
  }
}
