package com.lourish.wpoffer.repository.redis;

import org.springframework.data.repository.CrudRepository;

import com.lourish.wpoffer.domain.Offer;

/**
 * Interface for dynamic class generated by spring data redis
 * 
 * @author dave
 *
 */
public interface OfferRepository extends CrudRepository<Offer, String> {

}
